### ISSUE TITLE
[UI] Main View UI

### ISSUE THREAD

**Issue by beomsoo0** [chain-lightning/Oh-iOS#1]
## 💡 Issue
Main View UI 

## 📝 todo
- [x] 충전 상태 카드
- [x] 유저 잔액에 따른 UI
- [x] 내 주차장
- [x] 최근 충전 내역
- [x] 내가 줄인 탄소 발자국
- [x] 내가 줄인 탄소 발자국 설명 Modal
- [x] 충전하기 버튼 Gmail Style
