### ISSUE TITLE
[ERROR] 고쳐야 할 에러 사항들

### ISSUE THREAD

**Issue by beomsoo0** [chain-lightning/Oh-iOS#2]
## 💡 Issue
모든 에러들..

## 📝 todo
- [ ] Gmail Style 충전하기 버튼 모양 변경 시점
- [ ] QR 스캔 영역 중앙 맞추기
- [ ] 모든 폰트 피그마에 비해 전체적으로 더 얇음
- [ ] Main VC Network 통신을 위한 Logic 정리
