### ISSUE TITLE
[FEAT] Scan 기능 (QR, Card)

### ISSUE THREAD

**Issue by beomsoo0** [chain-lightning/Oh-iOS#3]
## 💡 Issue
QR, Credit Card Scan 기능 추가

## 📝 todo
- [x] QR Scan
- [ ] QR 정보로 Slot 불러오기
- [ ] Credit Card Scan
- [ ] Credit Card 정보 UI 표시하기

## 📑 Reference
https://itllbegone.tistory.com/7
