### ISSUE TITLE
[UI] BottomSheet View

### ISSUE THREAD

**Issue by beomsoo0** [chain-lightning/Oh-iOS#4]
## 💡 Issue
MaBottomSheet View UI 

## 📝 todo
- [ ] Top Bar Vertical Spacing 맞추기
- [ ] Top Round, Back Action 등을 Protocol로 사용할 순 없을까?
- [ ] View Height 고정값? 상대값?
